vlsisoc23:
    type: conf
    book: vlsisoc23
    authors:
        - me
        - ATC
        - GDM
    title: Synthesis of SFQ Circuits with Compound Gates
    year: 2023
    month: 10
    pdf: "papers/VLSI_SoC_2023.pdf"
    doi: ""
glsvlsi23:
    type: conf
    book: glsvlsi23
    authors:
        - me
        - GDM
    title: Compound Logic Gates for Pipeline Depth Minimization in Single Flux Quantum Integrated Systems
    year: 2023
    month: 6
    doi: 10.1145/3583781.3590287
    pdf: "papers/RSFQ_GLSVLSI23.pdf"
graphs_in_vlsi_book:
    type: book
    authors:
        - me
        - EGF
    publisher: springer_cham
    title: Graphs in VLSI
    published: True
    year: 2023
    isbn: 978-3-031-11047-4
    url: "https://link.springer.com/book/10.1007/978-3-031-11047-4"
tcad_qucts:
    type: journal
    book: tcad
    authors:
        - me
        - TJ
        - EGF
    title: QuCTS - single flux Quantum Clock Tree Synthesis
    doi: 10.1109/TCAD.2021.3123141
    pdf: "papers/QuCTS.pdf"
    year: 2022
    month: 10
    vol: 41
    num: 10
    pp: [3346, 3358]
tcad_sprout:
    type: journal
    book: tcad
    authors:
        - me
        - ARoy
        - MN
        - VS
        - EGF
    title: SPROUT - Smart Power ROUting Tool for Board-Level Exploration and Prototyping
    doi: 10.1109/TCAD.2021.3101411
    year: 2022
    vol: 41
    num: 7
    month: 7
    pp: [2263, 2275]
    pdf: "papers/SPROUT_TCAD.pdf"
tcad_exploration:
    type: journal
    book: tcad
    authors:
        - me
        - KX
        - MP
        - JSO
        - VS
        - EGF
    title: Power Delivery Exploration Methodology Based on Constrained Optimization
    year: 2020
    month: 9
    vol: 39
    num: 9
    pp: [1916, 1924]
    doi: 10.1109/TCAD.2019.2925397
    pdf: "papers/TCAD_Exploration.pdf"
mirror: 
    type: journal
    book: tcasi
    authors:
        - me
        - EGF
    title: Effective Resistance of Finite Two-Dimensional Grids Based on Infinity Mirror Technique
    year: 2020
    month: 9
    vol: 67
    num: 9
    pp: [3224, 3233]
    doi: 10.1109/TCSI.2020.2985652   
    pdf: "papers/TCASI_Inf_Mirror.pdf" 
truncated: 
    type: journal
    book: tcasi
    authors:
        - me
        - EGF
    title: Effective Resistance of Two-Dimensional Truncated Infinite Mesh Structures
    year: 2019
    month: 11
    vol: 66
    num: 11
    pp: [4368,4376]
    doi: 10.1109/TCSI.2019.2933749
    pdf: "papers/TCASI_Trunc.pdf" 
dac_sprout:
    type: conf
    book: dac21
    authors:
        - me
        - ARoy
        - MN
        - VS
        - EGF
    title: SPROUT - Smart Power ROUting Tool for Board-Level Exploration and Prototyping
    year: 2021
    month: 12
    pp: [283, 288]
    doi: 10.1109/DAC18074.2021.9586128
    pdf: "papers/SPROUT_DAC.pdf"
routing:
    type: conf
    book: iscas20
    authors:
        - me
        - ARoy
        - MN
        - VS
        - EGF
    title: Graph-Based Power Network Routing for Board-Level High Performance Systems
    year: 2020
    month: 10
    doi: 10.1109/ISCAS45731.2020.9181140
    pdf: "papers/ISCAS_Routing.pdf"
versatile:
    type: conf
    book: iscas18
    authors:
        - me
        - KX
        - MP
        - JSO
        - VS
        - EGF
    title: Versatile Framework for Power Delivery Exploration
    year: 2018
    month: 5
    doi: 10.1109/ISCAS.2018.8351478
    pdf: "papers/ISCAS_Exploration.pdf"
pemc:
    type: conf
    book: pemc
    authors:
        - me
        - AR
        - YLF
    title: Time Domain Optimization of Voltage and Current THD for a Three-Phase Cascaded H-Bridge Inverter
    year: 2016
    month: 9
    pp: [227, 232]
    doi: 10.1109/EPEPEMC.2016.7752002
    pdf: "papers/PEMC_THD.pdf"